# Generated by Django 4.2.10 on 2024-02-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='escudos/'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='uf',
            field=models.CharField(choices=[('PI', 'PIAUÍ'), ('AL', 'Alagoas'), ('BA', 'Bahia')], max_length=2),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.clube'),
        ),
    ]
