# Generated by Django 4.2.10 on 2024-02-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_clube_escudo_alter_clube_uf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='clube',
        ),
        migrations.RemoveField(
            model_name='titulo',
            name='clube',
        ),
        migrations.RemoveField(
            model_name='titulo',
            name='competicao',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='divisao_atual',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='escudo',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='uf',
        ),
        migrations.AddField(
            model_name='clube',
            name='divisao',
            field=models.CharField(choices=[('A', 'Série A'), ('B', 'Série B'), ('C', 'Série C'), ('D', 'Série D'), ('S', 'Sem Série')], default='S', max_length=64, null=True, verbose_name='Divisão'),
        ),
        migrations.AddField(
            model_name='clube',
            name='modalidade',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='clube',
            name='ano_fundacao',
            field=models.PositiveIntegerField(help_text='Ano que o Clube foi criado', verbose_name='Ano Fundação'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='nome',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Competicao',
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
        migrations.DeleteModel(
            name='Titulo',
        ),
    ]
