# Generated by Django 4.2.10 on 2024-02-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_jogador_clube_remove_titulo_clube_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clube',
            options={'verbose_name': 'Clube', 'verbose_name_plural': 'Clubes'},
        ),
        migrations.AddField(
            model_name='clube',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='escudos'),
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('numero_camisa', models.PositiveIntegerField()),
                ('foto', models.ImageField(null=True, upload_to='jogadores')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.clube')),
            ],
            options={
                'verbose_name_plural': 'Jogadores',
            },
        ),
    ]
