# Generated by Django 4.2.10 on 2024-02-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicos', '0001_initial'),
        ('project', '0004_alter_clube_options_clube_escudo_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicos.cidade'),
        ),
    ]
